title: 我的博客
theme: jekyll-theme-minimal
description: 记录学习与生活 | 技术分享 | 个人成长
baseurl: ""
url: "https://rabbity0114.github.io"

# 作者信息
author:
  name: Rabbity
  email: your-email@example.com

# 显示设置
show_downloads: false

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 分页设置
paginate: 10

# Markdown 设置
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
